on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  pull-requests: write
  contents: write
jobs:
  goreadme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Update readme according to Go doc
        uses: posener/goreadme@v1
        with:
          badge-codecov: 'true'
          badge-godoc: 'true'
          badge-goreadme: 'true'
